### ISSUE TITLE
淘宝 第二页 有 tab的 (viewpagger)

### ISSUE THREAD

**Issue by scaPEGoatno** [xmuSistone/android-vertical-slide-view#1]
我用了 TabLayout结果  点击 马上 返回 第一页

**Comment by xmuSistone** [comment]
请在滑动时action_down计算当前tab是否在scroll最顶部，并调用getparent.requestdisallowintercepttouchevent（true）

**Comment by scaPEGoatno** [comment]
咦...可是 上拉 到了 第二页  那Tab是在顶部了.. 我用了 TabLayout+viewpager  (第二页的布局) 我一点击 Tab切换  它就会 自己 滑动回第一页去了....

**Comment by xmuSistone** [comment]
TabLayout我没用过，你可以试试Indicator指示器，github上有很多开源项目。

**Comment by scaPEGoatno** [comment]
第二页的布局代码 ：
<LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

```
    <android.support.design.widget.TabLayout
        android:id="@+id/tab_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:tabIndicatorColor="@color/orange_f15353"
        app:tabSelectedTextColor="@color/orange_f15353"
        app:tabTextColor="@color/coffee_b98134"/>

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</LinearLayout>
```

上拉查看详情的 第二页 那个Tab已经在顶部了 我点击 Tab切换  可是会自动会第一页！！
