### ISSUE TITLE
关于底部viewpager疑问

### ISSUE THREAD

**Issue by zengqiang24** [xmuSistone/android-vertical-slide-view#11]
你好，我在底部fragment中嵌入了一个viewpager，发现底部不能滑动上去了哦 左右也不能滑

**Comment by xmuSistone** [comment]
这得看viewpager装入的是什么widget。
如果viewpager装入了webview，则webview对touch拦截不仅判断isAtTop，更要判断isAtRight。如果是listview，item里面没有水平滑动的item，则左右滑动无碍。如果是常规的scrollview，则viewpager可正常工作。
无论viewpager装载了哪一种widget，isAtTop拦截处理都是不可或缺的。viewpager不用定制，用原生的v4的就好，但是底层的每一个滑动控件都需要定制。为touch拦截配合。
你可以试试改一下看看。
如果确实改不了的话，你留下邮箱，我把改好的发你。

**Comment by zengqiang24** [comment]
好的 谢谢 我去试试
