### ISSUE TITLE
第二个Fragment放ViewPager的问题

### ISSUE THREAD

**Issue by LiaoFuYun** [xmuSistone/android-vertical-slide-view#13]
我在第二个Fragment中放了一个ViewPager,ViewPager中是两个Fragment,如果ViewPager中的fragment放滑动控件就上拉不了，不放滑动控件就正常，滑动控件我都用了你写的CusListView或者CusScrollView，事件分发真的好难

**Comment by xmuSistone** [comment]
底部的fragment都需要定制touch拦截，CustListView可用。由于CustScrollView只是为DragLayout的顶部view定制，底部若要用scrollView则需要定制额外的touch拦截策略。可仿照CustListView实现isAtTop方法
