### ISSUE TITLE
viewpager嵌套DragSlideLayout

### ISSUE THREAD

**Issue by lqfsharks** [xmuSistone/android-vertical-slide-view#14]
在viewpager里面嵌套DragLayout，好像viewpager自身不能左右滑动，请问有解决方案没？望不吝赐教。
补充一下，因为我在您已关闭的问题中发现有人跟我一样的疑问：就是Viewpager里面有一个Fragment，Fragment内部包含DragLayout，天猫APP中的商品详情页就是这样的应用场景。

**Comment by LiaoFuYun** [comment]
没有解决，放弃了

**Comment by xmuSistone** [comment]
此库被应用到这个App中了：http://android.myapp.com/myapp/detail.htm?apkName=com.lizi.app
应用场景是：DragLayout包含两个Fragment(顶部F1/底部F2)，底部的Fragment F2包含一个ViewPager，ViewPager装载了两个Fragment(F3和F4)，ViewPager无需额外定制，F3和F4要对touch的分发和拦截做额外定制如下：

Webview：
`private int scrollMode;
    private static final int MODE_IDLE = 0;
    private static final int MODE_HORIZONTAL = 1;
    private static final int MODE_VERTICAL = 2;
    private float downX, downY;
    private boolean needConsumeTouch = false;

    public DetailCustWebView(Context arg0, AttributeSet arg1, int arg2) {
        super(arg0, arg1, arg2);
        // 禁用缩放功能
        disableZoomController();
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {
            downX = ev.getRawX();
            downY = ev.getRawY();
            needConsumeTouch = true; // 默认情况下，listView内部的滚动优先，默认情况下由该listView去消费touch事件
            isAtTop = isAtTop();
            scrollMode = MODE_IDLE;
        } else if (ev.getAction() == MotionEvent.ACTION_MOVE) {
            if (!isAtTop && scrollMode == MODE_VERTICAL) {
                getParent().requestDisallowInterceptTouchEvent(true);
                return super.dispatchTouchEvent(ev);
            }
            else if (!needConsumeTouch || scrollMode == MODE_HORIZONTAL) {
                // 在最顶端且向上拉了，则这个touch事件交给父类去处理
                getParent().requestDisallowInterceptTouchEvent(false);
                return false;
            } else if (isAtTop) {
                // needConsumeTouch尚未被定性，此处给其定性
                // 允许拖动到底部的下一页，而且又向上拖动了，就将touch事件交给父view
                if (ev.getRawY() - downY > 2) {
                    // flag设置，由父类去消费
                    needConsumeTouch = false;
                    getParent().requestDisallowInterceptTouchEvent(false);
                    return super.dispatchTouchEvent(ev);
                }
            }

            if (scrollMode == MODE_IDLE) {
                float xDistance = Math.abs(downX - ev.getRawX());
                float yDistance = Math.abs(downY - ev.getRawY());
                if (xDistance > yDistance && xDistance > 4) {
                    scrollMode = MODE_HORIZONTAL;
                } else if (yDistance > xDistance && yDistance > 4) {
                    scrollMode = MODE_VERTICAL;
                }
            }
        }

        // 通知父view是否要处理touch事件
        getParent().requestDisallowInterceptTouchEvent(true);
        return super.dispatchTouchEvent(ev);
    }`


ListView:
`@Override
	public boolean dispatchTouchEvent(MotionEvent ev) {
		if (ev.getAction() == MotionEvent.ACTION_DOWN) {
			downX = ev.getRawX();
			downY = ev.getRawY();
			needConsumeTouch = true; // 默认情况下，listView内部的滚动优先，默认情况下由该listView去消费touch事件
			isAtTop = isAtTop();
			scrollMode = MODE_IDLE;
		} else if (ev.getAction() == MotionEvent.ACTION_MOVE) {
			if (!isAtTop && scrollMode == MODE_VERTICAL) {
				getParent().requestDisallowInterceptTouchEvent(true);
				return super.dispatchTouchEvent(ev);
			}
			else if (!needConsumeTouch || scrollMode == MODE_HORIZONTAL) {
				// 在最顶端且向上拉了，则这个touch事件交给父类去处理
				getParent().requestDisallowInterceptTouchEvent(false);
				return false;
			} else if (isAtTop) {
				// needConsumeTouch尚未被定性，此处给其定性
				// 允许拖动到底部的下一页，而且又向上拖动了，就将touch事件交给父view
				if (ev.getRawY() - downY > 2) {
					// flag设置，由父类去消费
					needConsumeTouch = false;
					getParent().requestDisallowInterceptTouchEvent(false);
					return super.dispatchTouchEvent(ev);
				}
			}

			if (scrollMode == MODE_IDLE) {
				float xDistance = Math.abs(downX - ev.getRawX());
				float yDistance = Math.abs(downY - ev.getRawY());
				if (xDistance > yDistance && xDistance > 4) {
					scrollMode = MODE_HORIZONTAL;
				} else if (yDistance > xDistance && yDistance > 4) {
					scrollMode = MODE_VERTICAL;
				}
			}
		}

		// 通知父view是否要处理touch事件
		getParent().requestDisallowInterceptTouchEvent(true);
		return super.dispatchTouchEvent(ev);
	}

	/**
	 * 判断listView是否在顶部
	 * 
	 * @return 是否在顶部
	 */
	private boolean isAtTop() {
		boolean resultValue = false;
		int childNum = getChildCount();
		if (childNum == 0) {
			// 没有child，肯定在顶部
			resultValue = true;
		} else {
			if (getFirstVisiblePosition() == 0) {
				// 根据第一个childView来判定是否在顶部
				View firstView = getChildAt(0);
				if (Math.abs(firstView.getTop()) < 2) {
					resultValue = true;
				}
			}
		}

		return resultValue;
	}`

**Comment by lqfsharks** [comment]
我说的应用场景是DragSlideLayout 被viewpager包裹哦，您举的例子是DragSlideLayout 包裹着viewpager。当DragSlideLayout 被外层的viewpager包裹着的时候，外层的viewpager是无法左右滑动的。

**Comment by xmuSistone** [comment]
那你稍等下，我现在事情不多，会帮你解决这个问题~

**Comment by lqfsharks** [comment]
非常感谢

**Comment by xmuSistone** [comment]
问题解决了，你留下邮箱地址吧。我邮件发给你~

**Comment by lqfsharks** [comment]
好的，807643335@qq.com，谢谢你的帮助！帮我解决了问题。

**Comment by xmuSistone** [comment]
代码发送到你邮箱了，请查收~
touch分发拦截策略做了优化。此仓库的代码后续也会更新上去~

**Comment by lqfsharks** [comment]
已测试，OK，是我想要的效果，以后有问题可以继续交流。

**Comment by AndroidFa** [comment]
可以给我一份吗？ 836434613@qq.com

**Comment by xmuSistone** [comment]
@AndroidFa 已发你邮箱
