### ISSUE TITLE
没法嵌套ViewPager

### ISSUE THREAD

**Issue by jiaoyaning** [xmuSistone/android-vertical-slide-view#16]
大神，能指点一下么?

**Comment by xmuSistone** [comment]
????能描述的清楚一些么

**Comment by jiaoyaning** [comment]
CustScrollView 嵌套了一个ViewPager ，ViewPager 里面是放的是图片，DragLayout可以正常上拉，ViewPager 就没办法滑动了，只卡在第一页。

**Comment by xmuSistone** [comment]
是不是手指放到viewpager上面就没法上下拖动了？

**Comment by jiaoyaning** [comment]
可以上下滑动，就是不能左右滑动了，viewpager没办法左右滑动。

**Comment by xmuSistone** [comment]
你拉取之前的代码看下，前几天被我改了，是要求draglayout支持外层viewpager滑动的。然而你现在又有内层viewpager的滑动需求。所以，很多时候应该你们自己看一下代码，然后做一些定制的

**Comment by jiaoyaning** [comment]
恩恩，谢谢大神

**Comment by xmuSistone** [comment]
你看下CustScrollView的history代码，就可以了。有一些差异的代码，github能比对出来的
