### ISSUE TITLE
CustScrollView放在第二个fragment中，到底部后能否禁止向上滑动呢

### ISSUE THREAD

**Issue by EmilyCYY** [xmuSistone/android-vertical-slide-view#17]
还望赐教~因为继续向上滑动的话，会出现空白页或者就是一部分底部view的重叠

**Comment by xmuSistone** [comment]
CustScrollView只能用在第一个Fragment中。如果第二个Fragment需要用到ScrollView，请仿照CustWebView自行实现touch定制
