### ISSUE TITLE
第二页放ListView的问题

### ISSUE THREAD

**Issue by wu21731** [xmuSistone/android-vertical-slide-view#21]
第二页放ListView，内容不能下滑，展示不了全部的数据，

**Comment by xmuSistone** [comment]
请仿照CustWebView自行实现Touch拦截订制

**Comment by wu21731** [comment]
使用CustListView也不行，怎么实现touch拦截订制

**Comment by xmuSistone** [comment]
前些日子我改了touch分发拦截策略，CustListView的代码并没有更新。
你自定义一个ListView，叫YourListView，然后把CustWebView的代码全部拷贝进去，然后把isAtTop那个函数重写一下就行了。
isAtTop可以直接参考CustListView的代码。

**Comment by wu21731** [comment]
按照你的方法写了，但是，还是不行，不能把fragment1滑下来，如果在ListView上面放一个其他的布局，滑动这个布局可以下来，

**Comment by xmuSistone** [comment]
你更新一下CustListView这个类，提了新代码
