### ISSUE TITLE
有提供禁止下拉吗？下拉到多少高度，出现下个页，怎么去设置？

### ISSUE THREAD

**Issue by super-hu** [xmuSistone/android-vertical-slide-view#23]

**Comment by yuxingfafu** [comment]
你好，哥们，后面你有实现这种功能么？就是开关控制是否上拉显示详情的

**Comment by xmuSistone** [comment]
@yuxingfafu 所有逻辑在DragLayout，页面切换以滑动高度和释放速度来算；禁止滑动，在tryCapture里面返回false就是禁止滑动了。
