### ISSUE TITLE
Fragment2中放置viewpager左右无法正常滑动

### ISSUE THREAD

**Issue by susuzero** [xmuSistone/android-vertical-slide-view#25]
你好，我在底部的fragment中放置了一个viewpager，viewpager包含2个子fragment，放置的分别是custlistview和custwebview，但是目前viewpager无法左右滑动，求解！

**Comment by xmuSistone** [comment]
ViewPager需要单独做touch分发和拦截。跟Fragment、自定义View协调合作才行。
你把邮箱留下，我把代码发你~

**Comment by susuzero** [comment]
@xmuSistone 谢谢，susuzero@126.com
