### ISSUE TITLE
实现京东商品详情页效果

### ISSUE THREAD

**Issue by zjc** [xmuSistone/android-vertical-slide-view#26]
你好，我现在在做京东的商品详情页效果，一个Activity中包含3个Fragment(简介，详情，评价)用ViewPager做容器，简介Fragment中用的DragLayout并且头部还有一个ViewPager，现在滑动到最后一张需要切换到详情，发现实现不了，移动的时候事件都被DragLayout中的ViewDragHelper处理了，求指点一二，万分感谢

**Comment by xmuSistone** [comment]
需要额外定制。一个Activity包含一个ViewPager，一个ViewPager包含三个Fragment；第一个Fragment是DragLayout，就可以了
