### ISSUE TITLE
锁屏情况下用as跑程序，会白板

### ISSUE THREAD

**Issue by ghost** [xmuSistone/android-vertical-slide-view#27]
今天使用了大神这个库，刚开始没发现又有什么问题，很顺利，有一次，用as跑应用，手机自动锁屏了，跑完之后，打开手机一看，直接白板，多试了几次，一直都有，请问这个是什么原因造成的呢

**Comment by xmuSistone** [comment]
这个我也不清楚怎么回事。锁屏状态下用AS跑程序，在现实生活中不会出现，暂时忽略这个问题吧
