### ISSUE TITLE
偶现白板的问题

### ISSUE THREAD

**Issue by ghost** [xmuSistone/android-vertical-slide-view#28]
在4.1.1的模拟器上，首页fragment里使用draglayout，当程序启动，快速切换到第二个tab，在切换会第一个tab的时候，首页就白板了，请问大神有什么好的解决办法吗，是因为库本身就存在这个问题吗？

**Comment by xmuSistone** [comment]
理论上不该出现这个问题的。你下载仓库里面的demo Apk试试，那个也会这样么？

**Comment by ghost** [comment]
demo里面跟我这种情况还不一样，我看你代码里面，有个地方写着有时候会默认白板，那个怎么复现呢？

**Comment by xmuSistone** [comment]
那个与此问题无关，你注释掉invalidate自然就看出问题所在了；
你的这个问题，我是真的没有遇到过，所以现在我也说不准问题出在哪里了
