### ISSUE TITLE
CustScrollView 高度发生变换，无法上拉

### ISSUE THREAD

**Issue by 88567free** [xmuSistone/android-vertical-slide-view#29]
CustScrollView  内部有个控件高度会发生变换，初始化后正常使用，如高度发生变换就无法上拉了，有什么解决方法吗？尝试requestLayout 并不起作用

**Comment by xmuSistone** [comment]
不要requestLayout; 
现在不会出现这个问题了吧？顶部Fragment包含ScrollView，是否滑动到底部，是手指触摸按下的时候来判断的，这个问题早就fix了，你看下是不是其他的代码你搞错了；你别改动代码，DragLayout和CustScrollView都不要碰，再试试看

**Comment by 88567free** [comment]
我是DragLayout 里直接包含了 CustScrollView + Fragment 这样就会产生bug？

**Comment by xmuSistone** [comment]
会产生bug！
请问，CustScrollView是否滑动到底部，怎么来界定？
Fragment是用来解耦的，Fragment好好的，你为何偏不喜欢它？我看不懂~~~
如果你坚持不用Fragment，不是不行，可以！但是也得理解了代码才能改造是不是。
你在ScrollView的外层再放一个FrameLayout，宽和高都match_parent，你再试试

**Comment by 88567free** [comment]
oh no 我两种方式都尝试了，用Fragment替换了。 内部有个listview 数据会发生变换 高度就变换了，frameView1 的 viewHeight 好像不会发生变换，导致了现在无法上拉了
