### ISSUE TITLE
某些情况上滑会提前进入下一个Fragment

### ISSUE THREAD

**Issue by LanKo-X** [xmuSistone/android-vertical-slide-view#3]
重现方法：
- Fragment_1 中有高度可变的元素
- 进入Fragment_1 后，先滑到它的最底部
- 然后让高度可变的元素高度变大
- 这时候，上滑时并未到达 Fragment_1 的底部就已经开始看见 Fragment_2 了

**Comment by xmuSistone** [comment]
额，如果你们的产品经理这么设计了，我建议你去把他打一顿。（哈哈）
你也可以看下代码的，touch的分发和拦截，是由draglayout去做，还是由scrollview自行处理，关键点就是在底部的ACTION_DOWN那里了。如果你需要定制的话，就改造一下就好。当前的Repository不会因为这个作修改了。

**Comment by LanKo-X** [comment]
我也认为这个重现方法很奇葩

不过这个问题应该很容易产生吧，像一些异步加载的图片之类的也会导致高度变化

**Comment by xmuSistone** [comment]
我了解你的意思了。目前的处理是第一次action_down去计算scrollview的滑动区间，后面就再也不计算了。

我已经想到一个还不错的解决办法，下周一我会提交新代码，到时你pull一下最新代码应该就不存在这个问题了。

**Comment by LanKo-X** [comment]
万分感谢

**Comment by xmuSistone** [comment]
你更新一下CustScrollView，这个bug应该解了。

**Comment by LanKo-X** [comment]
解决了，谢谢~

**Comment by ujffdi** [comment]
我刚下的DEMO，然后把代码拷到我的项目，还是会出现这个问题、时有时无。。

**Comment by ujffdi** [comment]
@xmuSistone

**Comment by xmuSistone** [comment]
请检查自己的代码逻辑 @ujffdi
