### ISSUE TITLE
滑动到底部后无法上滑

### ISSUE THREAD

**Issue by macjay** [xmuSistone/android-vertical-slide-view#32]
我现在的情况是上面一个fragment嵌套了scrollview~下面的frament是一个viewpager~viewpager包含2个fragment 每个fragment里面又是scrollview 我的scrollview是按照你代码里的custwebview写处理滑动事件~但是不能不能往上滑动，是用2台小米手机测试的。

**Comment by xmuSistone** [comment]
底部包含ViewPager的代码需要额外定制。你邮箱多少，我可以发你~

**Comment by macjay** [comment]
谢谢~~luosi@qiantanglicai.com

**Comment by suxinwei** [comment]
ViewPager额外定制的代码可以发给我一份么，suxinwei2012@163.com  谢谢！
