### ISSUE TITLE
高分屏适配问题

### ISSUE THREAD

**Issue by longtaoge** [xmuSistone/android-vertical-slide-view#4]
高分屏下，假如 第一页的 内容没有充满一屏的内容，底下会空出一大截，这个问题有没有好的解决办法
![](http://i.imgur.com/SalE3pu.png)

**Comment by xmuSistone** [comment]
这个Repository是为两个fragment分层解耦，如果一屏展示不下，并不影响向上拖拽的功能逻辑。
但是，你提出的这个问题，并不是代码框架的问题，是UI设计湿的问题。
屏幕这么大，何必大废周章再去分屏呢？
如果真的想去分屏，你大可用拐弯抹角的方法去填满第一个fragment。填满屏幕的方法有千千万，需要产品设计师去想~
