### ISSUE TITLE
点击按钮跳转下一页

### ISSUE THREAD

**Issue by 401885064** [xmuSistone/android-vertical-slide-view#8]
我想实现点击按钮跳转下一页，请问要怎么弄？，能提供一个方法吗？

**Comment by xmuSistone** [comment]
可以给draglayout添加一个公共方法
public void switchToBottom(){
    animTopOrBottom(frameView1, -101);
}

参见https://github.com/xmuSistone/android-vertical-slide-view/issues/7

**Comment by 401885064** [comment]
非常感谢！
